### ISSUE TITLE
Song Command is not working ⛔️

### ISSUE THREAD

**Issue by Kerala-Boy** [TOXIC-DEVIL/Felix-Userbot#3]
Hey @TOXIC-DEVIL @TOXIC-DEVIL-ABHINAV!👋
Song Command is not working... Please Fix it 😟
😟😟

**Comment by TOXIC-DEVIL** [comment]
> Hey @TOXIC-DEVIL @TOXIC-DEVIL-ABHINAV!👋
> Song Command is not working... Please Fix it 😟
> 😟😟

Oii @Kerala-Boy! ✅️
We Have **[Fixed It!!](https://github.com/TOXIC-DEVIL/Felix-Userbot/commit/ee71930681884cc4821c8b2d3451182cbd7c08f9#commitcomment-53117426) Thank You For Informing 😘

**Comment by Kerala-Boy** [comment]
> > Hey @TOXIC-DEVIL @TOXIC-DEVIL-ABHINAV!👋
> > Song Command is not working... Please Fix it 😟
> > 😟😟
> 
> Oii @Kerala-Boy! ✅️
> We Have **[Fixed It!!](https://github.com/TOXIC-DEVIL/Felix-Userbot/commit/ee71930681884cc4821c8b2d3451182cbd7c08f9#commitcomment-53117426)** Thank You For Informing 😘

Welcome 🙂
